# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "SwiftRadioUISnapshots")
  end

  desc "Release beta"
  lane :beta do
    increment_build_number
    build_app(scheme: "SwiftRadio")
    upload_to_testflight
  end

  desc "Release for real"
  lane :release do
    capture_screenshots(scheme: "SwiftRadioUISnapshots")
    build_app
    upload_to_app_store       # Upload the screenshots and the binary to iTunes
    slack                     # Let your team-mates know the new version is live
  end
end
