# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots, no cover"
  lane :screenshots do
    capture_screenshots(
    scheme: "SwiftRadioSnapshots",
    output_simulator_logs: true,
    clear_previous_screenshots: false,
    )
  end

  desc "Generate new localized screenshots, with cover"
  lane :covershots do
    capture_screenshots(
    scheme: "SwiftRadioCoverSnapshots",
    output_simulator_logs: true,
    clear_previous_screenshots: false,
    )
  end

  desc "Add frames"
  lane :frame do
    frame_screenshots(gold: true) 
  end

  desc "Release beta"
  lane :beta do
    increment_build_number
    build_app(scheme: "SwiftRadio")
    upload_to_testflight
  end

  desc "Release for real"
  lane :release do
    increment_build_number
    build_app(
      scheme: "SwiftRadio",
    )
    upload_to_app_store(       # Upload the screenshots and the binary to iTunes
      username: "joe.mcmahon@gmail.com",
    )
  end
end
